name: tag release after PR merge

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Branch to merge from'
        required: true
        default: 'main'
      target_branch:
        description: 'Branch to merge into'
        required: true
        default: 'humble'
      bump_version:
        description: 'Version bump type'
        required: true
        default: 'patch'
      repository_owner:
        description: 'Repository owner (org or user)'
        required: false
        default: 'autowarefoundation'

jobs:
  tag-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Run
        uses: sasakisasaki/autoware-github-actions/release-new-tag-when-merged@testing/release-new-version
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          commit_sha: ${{ github.event.pull_request.merge_commit_sha }}
